config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "callbacks"}
  get "home/index"

  resources :buckets do
    resources :notes
  end

  root "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Bucket, user_id: user.id
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bucket.rb
class Bucket < ApplicationRecord
  has_many :notes, dependent: :destroy
  belongs_to :user
  validates :user, presence: true
  validates :title, presence: true,
                    length: {minimum: 2}
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :bucket
  validates :name, presence: true,
                    length: {minimum: 2}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :omniauthable

  has_many :buckets, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    flash[:warning] = exception.message
    redirect_to root_path
  end
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action require: :user

  def index
    @buckets = Bucket.where(user_id: current_user.id)
  end

  def show
    @bucket = Bucket.find(params[:id])
    authorize! :show, @bucket
  end

  def new
    @bucket = Bucket.new
  end

  def edit
    @bucket = Bucket.find(params[:id])
  end

  def create
    @bucket = Bucket.new(bucket_params)
    @bucket.user = current_user
    authorize! :create, @bucket

    if @bucket.save
      redirect_to @bucket
    else
      render "new"
    end
  end

  def update
    @bucket = Bucket.find(params[:id])
    authorize! :update, @bucket

    if @bucket.update(bucket_params)
      redirect_to @bucket
    else
      render "edit"
    end
  end

  def destroy
    @bucket = Bucket.find(params[:id])
    @bucket.destroy

    redirect_to buckets_path
  end

  private

  def bucket_params
    params.require(:bucket).permit(:title, :text)
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @bucket = Bucket.find(params[:bucket_id])
    @note = @bucket.notes.create(note_params)
    redirect_to bucket_path(@bucket)
  end

  def destroy
    @bucket = Bucket.find(params[:bucket_id])
    @note = @bucket.notes.find(params[:id])
    @note.destroy
    redirect_to bucket_path(@bucket)
  end

  private

  def note_params
    params.require(:note).permit(:name, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/buckets/_form.html.erb
<%= form_with model: @bucket, local: true do |form| %>
 
  <% if @bucket.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@bucket.errors.count, "error") %> prohibited
        this bucket from being saved:
      </h2>
      <ul>
        <% @bucket.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/buckets/_menu.html.erb
<p>
  <%= link_to 'Home', home_index_url %>

  <%= link_to 'List', buckets_path %>
  <%= link_to 'New', new_bucket_path %>

  <% if user_signed_in? %>
    <%= link_to 'Edit', edit_user_registration_path %>
    <%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %>
  <% else %>
    <%= link_to 'Sign in', new_user_session_path %>
    <%= link_to 'Sign up', new_user_registration_path %>
  <% end %>
</p>

app/views/buckets/edit.html.erb
<h1>Edit bucket</h1>

<%= render 'form' %>

app/views/buckets/index.html.erb
<h1>List of buckets</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @buckets.each do |bucket| %>
    <tr>
      <td><%= bucket.title %></td>
      <td><%= bucket.text %></td>
      <td><%= link_to 'Show', bucket_path(bucket) %></td>
      <td><%= link_to 'Edit', edit_bucket_path(bucket) %></td>
      <td><%= link_to 'Destroy', bucket_path(bucket),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/buckets/new.html.erb
<h1>new bucket</h1>

<%= render 'form' %>

<%= link_to 'Back', buckets_path %>

app/views/buckets/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @bucket.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @bucket.text %>
</p>

<h2>Notes:</h2>
<%= render @bucket.notes %>

<h2>Add a note:</h2>
<%= render 'notes/form' %>

<%= link_to 'Back', buckets_path %>
<%= link_to 'Edit', edit_bucket_path(@bucket) %>
<%= link_to 'Destroy', bucket_path(@bucket),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

app/views/home/index.html.erb
<h1>Home is where the home#index is</h1>
<p>Our landing page</p>

<%= link_to 'List Buckets', controller: 'buckets' %>
<%= link_to 'New bucket', new_bucket_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demooauth2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'buckets/menu' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: [ @bucket, @bucket.notes.build ], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/notes/_note.html.erb
  <p>
    <strong>Note:</strong>
    <%= note.name %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= note.body %>
  </p>

  <p>
  <%= link_to 'Delete note', [note.bucket, note],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  </p>